### ISSUE TITLE
Would love to be able to export my capital gains report for my accountant

### ISSUE THREAD

**Issue by guylepage3** [blockstackinc/blocktax#4]
Hi, I'm a big fan of your app. Super simple and it "just works."

I have a couple of wants from your app so that I may pass some data along to my accountant.

1. I would love to be able to export my "capital gains" report in a `.csv` file for my accountant. This is something they requested from me. Turns out, your app solves that problem. 👏🏻
2. When I first "signed in" with my Blockstack ID, I landed on the home page and for a second I was unaware what to do next. It would be nice to see a welcome message with a large button telling me to connect to my Coinbase account. This would make the process a bit smoother.

Other than that, I love how simple and clean your app is. This is a real world app that everyone in the crypto space could use.

Great work!

**Comment by JackNeto** [comment]
Thank you for the nice feedback. I'm actively working on the app doing some UI and workflow fixes and I just wanted to let you know that the CSV export is high on the priority list so it will be coming soon.

**Comment by guylepage3** [comment]
>I just wanted to let you know that the CSV export is high on the priority list so it will be coming soon.

This is great news! I'm looking forward to it. 😄

**Comment by JackNeto** [comment]
I've added the CSV export. You can check it out at https://entaxy.io (new name)

**Comment by guylepage3** [comment]
@JackNeto Nice! will do sir. 😄

**Comment by guylepage3** [comment]
Oh.. Somehow the getting started process got a lot more complicated.. Before there was a simple and smooth process to connect my Coinbase data to the app. Now I have to go search out some API items on Coinbase. This now becomes a product that my accountant will not be able to use.. Is there a way to go back to the old simple way to access the Coinbase data?

**Comment by JackNeto** [comment]
Adding the conversation here for reference:
